# Generated by Django 4.0.5 on 2022-07-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Genre name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Genre description')),
            ],
        ),
        migrations.CreateModel(
            name='Publishing_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Publishing house')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Publishing house description')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Book name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Book description')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='directory.genre', verbose_name='Genre')),
                ('publishing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publishing', to='directory.publishing_house', verbose_name='Publishing')),
            ],
        ),
    ]
