# Generated by Django 4.0.5 on 2022-07-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Author')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Author description')),
            ],
        ),
    ]
