# Generated by Django 4.0.5 on 2022-07-09 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.PROTECT, related_name='author', to='directory.author', verbose_name='Author'),
            preserve_default=False,
        ),
    ]
