# Generated by Django 4.0.5 on 2022-07-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_remove_book_genre_book_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Series')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Series description')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.CharField(default='fill me later', max_length=30, verbose_name='Book series'),
            preserve_default=False,
        ),
    ]
