# Generated by Django 4.0.5 on 2022-08-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_salesbooks_book'),
        ('directory', '0006_series_book_series'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
