# Generated by Django 4.0.5 on 2022-08-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_bookincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Session ID'),
        ),
    ]
