# Generated by Django 4.0.5 on 2022-08-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cart_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Processing', 'processing'), ('Paid', 'paid'), ('Delivery', 'delivery'), ('Problemm', 'problemm'), ('Cancel', 'cancel')], default='processing', max_length=15),
        ),
    ]
