# Generated by Django 4.0.5 on 2022-08-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cart notes'),
        ),
    ]
