# Generated by Django 4.0.5 on 2022-08-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cart_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Cart notes'),
        ),
    ]
