# Generated by Django 4.0.5 on 2022-08-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_cart_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Total Price'),
        ),
    ]
