# Generated by Django 4.0.5 on 2022-08-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_cart_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Total_price',
            new_name='total_price',
        ),
    ]
