# Generated by Django 4.0.5 on 2022-08-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0006_series_book_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Book name')),
                ('series', models.CharField(max_length=30, verbose_name='Book series')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Book description')),
                ('author', models.ManyToManyField(related_name='author', to='directory.author', verbose_name='Author')),
                ('genre', models.ManyToManyField(related_name='genres', to='directory.genre', verbose_name='Genre')),
                ('publishing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publishing', to='directory.publishing_house', verbose_name='Publishing')),
            ],
        ),
    ]
