# Generated by Django 4.0.5 on 2022-08-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Book series'),
        ),
    ]
