# Generated by Django 4.0.5 on 2022-07-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0006_series_book_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ManyToManyField(related_name='sale_book', to='directory.book', verbose_name='Sale_book')),
            ],
        ),
        migrations.CreateModel(
            name='SalesAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.ManyToManyField(related_name='top_author', to='directory.author', verbose_name='Top_author')),
            ],
        ),
    ]
