# Generated by Django 4.0.5 on 2022-07-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesauthors',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Sales number'),
        ),
    ]
