# Generated by Django 4.0.5 on 2022-07-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_series_book_series'),
        ('sales', '0003_salesauthors_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesauthors',
            name='authors',
            field=models.ManyToManyField(related_name='top_author', to='directory.author', verbose_name='top_author'),
        ),
    ]
