# Generated by Django 4.0.5 on 2022-07-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_salesauthors_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbooks',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Sales book description'),
        ),
        migrations.AddField(
            model_name='salesbooks',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Sales book number'),
        ),
        migrations.AlterField(
            model_name='salesauthors',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Sales author description'),
        ),
        migrations.AlterField(
            model_name='salesauthors',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Sales author number'),
        ),
    ]
