# Generated by Django 4.0.5 on 2022-08-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('sales', '0005_salesbooks_description_salesbooks_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbooks',
            name='book',
            field=models.ManyToManyField(related_name='sale_book', to='books.book', verbose_name='Sale_book'),
        ),
    ]
