# Generated by Django 4.0.5 on 2022-08-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_salesbooks_number_alter_salesbooks_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesauthors',
            name='number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Sales author number'),
        ),
    ]
