# Generated by Django 4.0.5 on 2022-08-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salesauthors_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbooks',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Sales picture'),
        ),
    ]
