# Generated by Django 4.0.5 on 2022-08-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_salesbooks_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesauthors',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Sales picture'),
        ),
    ]
